### ISSUE TITLE
Add CI Test for Jenkins Slave Ansible

### ISSUE THREAD

**Issue by sherl0cks** [rht-labs/labs-ci-cd#105]
Make sure that it can actually do ansibley things in a pipeline

**Comment by JoshuaTPritchett** [comment]
@sherl0cks I can do this as well as the NPM test. Would you like a separate test pipeline?

**Comment by sherl0cks** [comment]
Yea I think they need to be different. The question is precisely what is tested for the ansible one, it may be as simple as ansible --version

**Comment by JoshuaTPritchett** [comment]
I think these could be good starting candidates:
- [ ] Localhost ad-hoc commands
- [ ] Environment Variable based commands (maybe some stuff with Sonarqube?)

Thoughts?

**Comment by sherl0cks** [comment]
@JoshuaTPritchett I think you are at a point where you can take on some more advanced stuff. Could you come up with a proposal here? Im preparing for big customer next week and wont be able to dig into this for at least 1 more week.

 We just need to validate that the image was built, works as a slave, and has ansible installed. We need those tests to run in a pipeline buildconfig after the inventory is run (look at the java pipeline for an example). Finally, we need the CI job (the Jenkinsfile in the root dir of this repo) to validate that the pipeline buildconfig for ansible to complete. That will require changing some of the test logic.

**Comment by sherl0cks** [comment]
Looks like we crossed in mid air. I'd stay away from complex ansible operations. We just need to test that the slave comes up in pipeline and has latest ansible.

Sonarqube is a whole different beast, but if you have interest in it, we have a long list of issues related

**Comment by JoshuaTPritchett** [comment]
@sherl0cks I am not using RHEL on my home box. I also am running Minishift so doing it within a VM will be super dicey. In order for me to complete this ticket, I need to be able to build the Ansible Slave. Ideas?

**Comment by sherl0cks** [comment]
if you want to run local, try the CDK, which is minishift on rhel. you can sign up for a free rhel subscription. https://developers.redhat.com/products/cdk/overview/

if that proves a challenge, we can work on an OpenShift Online account to collaborate

**Comment by springdo** [comment]
There is a whole bigger discussion on CI for the Slaves in COP land https://github.com/redhat-cop/containers-quickstarts/issues/82

On this basis and given we're moving all our slaves there, let's have the discussion there and not here. Closing
