### ISSUE TITLE
Jenkins Tagging

### ISSUE THREAD

**Issue by JoshuaTPritchett** [rht-labs/labs-ci-cd#116]
The latest image for Jenkins within the Red Hat Container catalog tag is v3.6 for all Jenkins images.

https://access.redhat.com/containers/#/search/jenkins

**Comment by sherl0cks** [comment]
@JoshuaTPritchett that is to handle an issue related to the `oc` client breaking deployments, this repo should be tagged to `v3.7`. There is a `3.6` tag if needed: https://github.com/rht-labs/labs-ci-cd/releases/tag/v3.6.0

**Comment by JoshuaTPritchett** [comment]
Ah I see, I am doing development on Minishift at home, all of the Jenkins image builds seem to fail, 3.6 or not.

**Comment by sherl0cks** [comment]
ok - do share the build failure log, that can be helpful

**Comment by JoshuaTPritchett** [comment]
#### Problem

Jenkins `BuildConfig` fails to start:

![screenshot from 2018-01-30 22-20-51](https://user-images.githubusercontent.com/10160441/35603572-f03b1708-060b-11e8-8b17-d1ccf6cb1cfe.png)

![image](https://user-images.githubusercontent.com/10160441/35603624-2a5c30e8-060c-11e8-95c8-d277309bd9d9.png)

#### Potential Reason

Within
```
params/jenkins/buiild
```
The ImageStreamTag that is being used is v3.7, however, based on the images above, Minishift only delivers with v2,1,latest within the OpenShift namespace.

**Comment by sherl0cks** [comment]
Interesting. I'll need to double check what ive been doing on our clusters - we have it this type of thing with inage tags in 3.7 and again, its related to that issue I mentioned with 3.7 oc client breaking backwards conpatibility. 

For now, you can run the bellow command, which should pull all the tags into the openshift namespace:

oc import-image openshift/jenkins --from=registry.access.redhat.com/openshift3/jenkins-2-rhel7 --confirm --all

**Comment by JoshuaTPritchett** [comment]
Sounds good, I went ahead and just changed the stream tag to latest locally to test #115. I will make sure to import the new image moving forward.
