### ISSUE TITLE
Move Jenkins Ansible Slave Back to rpm install

### ISSUE THREAD

**Issue by sherl0cks** [rht-labs/labs-ci-cd#138]
Currently using pip install to get a devel release of ansible 2.5. Once 2.5 GA's let's move back to old way
https://github.com/rht-labs/labs-ci-cd/blob/5a952d2af3cba87d9f52c21f0890213a7021cf1e/docker/jenkins-slave-ansible/Dockerfile

**Comment by springdo** [comment]
Not needed as we're going to point to the cop version; in which this is fixed!
