### ISSUE TITLE
Add license headers to all source files

### ISSUE THREAD

**Issue by InfoSec812** [rht-labs/labs-ci-cd#147]
See [Issue 169](https://github.com/redhat-cop/casl-ansible/issues/169) on casl-ansible

**Comment by oybed** [comment]
For CASL (including both casl-ansible and infra-ansible), we discussed this as part of our weekly CASL call last week and agreed that we will not add the license info to every file. However, we will enforce that each role has the necessary format for documentation, including the license info - as seen here:
https://github.com/oybed/infra-ansible/tree/dns-rework7/roles/dns#license

**Comment by InfoSec812** [comment]
And on this week's CASL call I was explaining that there are several public sector clients which this would not be sufficient for. Eric and the rest discussed and said that as long as:

1. It can be automated using a Git hook
2. It was just the short-version header

They felt like this was acceptable.

**Comment by oybed** [comment]
@InfoSec812 for CASL that's a discussion I should be part of (and this is all news to me and no notes has been captured about it). Let's re-discuss when we get a chance.

**Comment by InfoSec812** [comment]
Sounds like a plan @oybed

**Comment by sherl0cks** [comment]
let me know where this lands. we'll follow suit with casl.

**Comment by sherl0cks** [comment]
Closing this issue as it seems to be dead. Feel free to reopen when/if needed.
