### ISSUE TITLE
Change Rolling deployment to Recreate deployment

### ISSUE THREAD

**Issue by InfoSec812** [rht-labs/labs-ci-cd#154]
The Nexus template uses "Rolling" deployment which means that it will try to start the replacement Pod before the it stops the existing Pod. Since Nexus uses a RWO PVC this Rolling deployment will fail. Change it to use a Recreate deployment.

https://github.com/rht-labs/labs-ci-cd/blob/c7381201586f7ee8b7ca81a36db35b403c22dc59/openshift-templates/nexus/template.json#L87

**Comment by sherl0cks** [comment]
resolved by #155
