### ISSUE TITLE
Separate Inventory Into Projects vs Tools vs Apps

### ISSUE THREAD

**Issue by sherl0cks** [rht-labs/labs-ci-cd#159]
In order to promote the practice that projects are a more privileged object. Should also update labels on templates to make it easier to `oc delete all -l foo=bar` instead of `oc delete project`.

This also means moving app config to `.openshift-applier` directories in app source code, so we'll need to address the issue of how you stand up labs-ci-cd with those apps for things like CI, since we need an app to go through the pipeline for regression testing.

**Comment by springdo** [comment]
yeah good shout! I think if we're going to be going down the .openshift-applier route; we're going to end up splitting out the app deploys, builds etc. This will be cool as will make the CI/CD project lighter and more accessible to all the consulting folk. Maybe we should update the ticket to  `Projects vs Tools vs Apps` - just a suggestion so feel free to ignore like!

**Comment by springdo** [comment]
I think the work on enablement would put me in a good position to take on some of this chunk of work if you want to farm it out @sherl0cks? Will get it working in enablement and share back to here

**Comment by sherl0cks** [comment]
that is ideal =) happy to review once you have something

**Comment by sherl0cks** [comment]
any chance you can take a look at this @springdo ?

**Comment by springdo** [comment]
Aye - actually started working on it today as a matter of fact! 

I reckon this will be done piece by piece as when I started it; i realised this is the beginning of reworking large chunks of this repo. Be good to chat about the direction I take after the first _easy part_ of the PR comes through
