### ISSUE TITLE
Let's make Jenkins pretty again!

### ISSUE THREAD

**Issue by springdo** [rht-labs/labs-ci-cd#171]
Play with https://github.com/afonsof/jenkins-material-theme and see if we can automate it's setup to make Jenkins a bit more visually appealing WITHOUT reducing his performance

**Comment by InfoSec812** [comment]
I thought this is why we use Blue Ocean?

**Comment by sherl0cks** [comment]
@springdo this is quite old and now falls in https://github.com/rht-labs/s2i-config-jenkins. Blue Ocean has gotten much more performant in recent releases, but if you still feel this is valid, please do open a new issue in the new repo
