### ISSUE TITLE
Example application

### ISSUE THREAD

**Issue by rdebeasi** [rht-labs/labs-ci-cd#198]
I'd love to see example code for an application built with Labs CI-CD. This would help provide guidance for application-related concerns, such as:
- "Forking" labs-ci-cd for your project
- Creating an `.openshift-applier` directory with the resources needed to run your application
- Creating a Jenkinsfile that utilizes the builder pods set up by labs ci-cd
- Pointing the ci-cd pipelines to your repo and setting up web hooks

One starting point for this work would be [map-booster](https://github.com/map-booster), which @pcarney8, @nmalvankar and I built as a demo for a recent residency. What do folks think about making this an "official" demo project? Are there changes or additions you'd like to see?

**Comment by rdebeasi** [comment]
Looks awesome! For folks reading along, todolist-fe is here: https://github.com/springdo/todolist-fe

I love the idea of using one repo for enablement and a CI-CD "demo app". The test coverage and readability of the code is awesome. Building and hosting in one Node.js + httpd image is simple and clear, especially for enablement purposes. On the other hand, using the [npm build slave](https://github.com/redhat-cop/containers-quickstarts/tree/master/jenkins-slaves/jenkins-slave-npm) to build and httpd S2I to host is probably more efficient and would produce smaller containers. Maybe this approach could be in an "advanced" example somewhere. Do folks prefer one approach over the other? Both, for different use cases? Something completely different that we didn't think of?

Is build.sh basically the Jenkinsfile? If so, could we call it that?

All that said, I'm mostly wondering:
- Can I help with this demo app at all?
- Could we make the demo app an "official Labs thing" by moving it to the rht-labs org and linking to it from the appropriate READMEs? Are there changes/additions that folks would like to see before those changes are made?

**Comment by rdebeasi** [comment]
Just had a quick chat with Dónal about this. Here are the tasks we came up with:

- [ ] Create a "solution" branch of https://github.com/rht-labs/todolist-fe, based on the `jenkinsfile` branch in that repo, with the completed project. (This would include security scans, code coverage checks, and other features that aren't present in the master branch.)
- [ ] Create a labs-ci-cd "quick start" guide that expands on this line from the readme:
  > Apps can be added also by applying their Jenkinsfile as a buildConfig with an example (java-app) is included as a reference.
- [ ] Set up the todo app to use separate build (npm) and httpd (deploy) pods.

  This quick start guide could be a super-condensed version of the enablement docs. It could be separate from the readme. A user with basic command line knowledge, access to an OpenShift cluster, and the "solution branch" should be able to follow these step-by-step instructions and have the demo app + pipeline running in 15 minutes or so.

I'd also add:
- [ ] Create prominent links between the enablement docs, todolist-fe, and labs-ci-cd to make it clear that they all go together.
- [ ] In the labs-ci-cd readme, explain how `.openshift-applier` works.

**Comment by pcarney8** [comment]
can we close issue and open a separate repo? 

I don't think CI/CD should be showing you how to setup `.openshift-applier` and an App. An _actual_ app example repo should be doing that.

**Comment by rdebeasi** [comment]
Yeah, I was definitely thinking this example would live in a separate repo. I'm working on [https://github.com/rdebeasi/magicbox-maps-prototype/tree/openshift](this magicbox-related example], which has a Jenkinsfile, `.openshift-applier` directory, separate build and deploy pods, etc. This repo could be used as-is, or the OpenShift bits could be moved to a different "example" repo.

Or, maybe work on improving new enablement materials could produce a good example of how to use the applier!

Anyway, I'm happy to close this issue as long as the need for an example repo is tracked somewhere. A Trello card, maybe?

**Comment by pcarney8** [comment]
@rdebeasi can we close this? a lot of example applications that also use the applier and jenkins are in https://github.com/redhat-cop/containers-quickstarts now and should probably continue to be put there or into their own repos. We can open an issue in containers-quickstarts or just make another repo under the rht-labs org and start adding issues there.

**Comment by rdebeasi** [comment]
Sure - closing!
