### ISSUE TITLE
Sonatype Nexus REST API Changes in Version >= 3.8.0

### ISSUE THREAD

**Issue by InfoSec812** [rht-labs/labs-ci-cd#199]
The REST API paths in Sonatype Nexus have changed starting with 3.8.0. They have changed from:

`/service/siesta/rest/v1/script`

To

`/service/rest/v1/script`

I recommend cutting a release with the Nexus version hard-coded at 3.7.x and then for future versions of this project we use the new REST API paths via a newer version of the `configure-nexus` role.

**Comment by sherl0cks** [comment]
resolved in #259
