### ISSUE TITLE
Figure out why push to internal registry fails intermittently

### ISSUE THREAD

**Issue by InfoSec812** [rht-labs/labs-ci-cd#2]
Sometimes during builds of various images we get a failure:

```
Successfully built 1b59938f722b
Pushing image 172.30.1.1:5000/labs-ci-cd/mvn-build-pod:latest ...
error: build error: Failed to push image: unauthorized: authentication required
```

We need to determine why and how to prevent it.

**Comment by InfoSec812** [comment]
Additionally, this can usually be resolved by triggering a new build. The subsequent build usually succeeds.

**Comment by sherl0cks** [comment]
see #42 closing this issue
