### ISSUE TITLE
Create Selenium Jenkins Agents for Chrome and Firefox

### ISSUE THREAD

**Issue by InfoSec812** [rht-labs/labs-ci-cd#235]
As a DevOps team member, I need to be able to run Selenium tests from within Jenkins pipelines. In order to run Selenium tests, I need a Jenkins Agent which can execute Google Chrome and Firefox web browsers in a "headless" environment using Xvfb running as a non-root user.

**Comment by springdo** [comment]
yo @InfoSec812 - we have the `jenkins-npm-slave` which has latest chrome installed in it; and if you look at the enbalement material we do some headless selenium testing against chrome. On our current residency we're using Chrome headless / Firefox headless using the `Zalenium` stuff from upstream container-quickstarts. Happy to share our code for that as we've integrated it into a `mvn` build toolchain and a `npm` one. Also Emanuel has ported the config to our local labs-ci-cd so am sure he can share his findings on getting it running. Pretty sure he encountered some issues and privallege stuff

**Comment by sherl0cks** [comment]
seems like this stuff should live in quickstarts now. closing this issue. Feel free to open in quickstarts
