### ISSUE TITLE
Update Docker image and template to support LDAP auth on SonarQube

### ISSUE THREAD

**Issue by InfoSec812** [rht-labs/labs-ci-cd#245]
Discovered during a customer consulting engagement that the LDAP config is incomplete. Need to update Dockerfile, scripts, config files, and templates templates to allow for LDAP integration with IdM/FreeIPA.

**Comment by oybed** [comment]
This issue is being addressed by PR https://github.com/redhat-cop/containers-quickstarts/pull/177

**Comment by sherl0cks** [comment]
sonar lives in quickstarts now. closing
