### ISSUE TITLE
Customer feedback: too heavy to extend or start new project

### ISSUE THREAD

**Issue by alberttwong** [rht-labs/labs-ci-cd#249]
There has to be an easier way.

**Comment by sherl0cks** [comment]
Albert this repo really isn't designed for customer's to use without support and guidance from our team. Its really an internal artifact that we're building in the open.

That said, can you elaborate on what your customer is trying to acheive and the specific challenges they had?

**Comment by alberttwong** [comment]
@sherl0cks Justin, contact me internally.   It was a customer that went through labs and now they're trying to do it in their own environment.

**Comment by sherl0cks** [comment]
closing based on today's conversation. for future readers, labs ci/cd is not intended to be a lightweight getting started experience on openshift, but an operationally robust approach to container driven CI/CD. for the lightweight getting started experience, see https://github.com/redhat-developer/odo
