### ISSUE TITLE
Consider Moving from {{ playbook_dir }} to {{ inventory_dir }}

### ISSUE THREAD

**Issue by sherl0cks** [rht-labs/labs-ci-cd#261]
If distribute Labs CI/CD via galaxy, moving to inventory dir would allow consumers to write playbooks like the one found in #260 , instead of requiring Labs CI/CD to maintain such playbooks. This would allow consumers to reuse our inventory (and its excellent filter tagging), reducing their maintenance overhead.

**Comment by sherl0cks** [comment]
See https://github.com/sherl0cks/container-pipelines/tree/secure-spring-boot-pipeline as an example of how this would work.

**Comment by oybed** [comment]
+100
We have always promoted using `inventory_dir` as part of `openshift-applier` work, and it is reflected in all the original `openshift-applier` and most of CoP work as well + it is also in the applier [tests](https://github.com/redhat-cop/openshift-applier/tree/master/tests)

**Comment by sherl0cks** [comment]
Just spoke with @pcarney8 . He is OK with moving to inventory dir. I will send a PR for this.
