### ISSUE TITLE
Slave images won't launch in Jenkins

### ISSUE THREAD

**Issue by springdo** [rht-labs/labs-ci-cd#275]
Issue: 
Trying to launch a custom built slave ie `jenkins-slave-npm` to run a build. Jenkins freezes trying to launch the agent and connect to it therefore build hangs.

Resolution:
Set the image tag to `latest` for each of the slaves so Jenkins knows what one to launch. PR #274 should close this issue. 

@pcarney8  - be good to get this in when you get a moment as labs-ci-cd is borked until we solve.

**Comment by pcarney8** [comment]
closed due to #274
