### ISSUE TITLE
Jenkins on OpenShift 4.x OAuth Integration Has Issues

### ISSUE THREAD

**Issue by InfoSec812** [rht-labs/labs-ci-cd#276]
The OAuth integration for Jenkins is not working in OpenShift 4.x.

We need to see if manually creating the OAuth resource might resolve the issue.

**Comment by makentenza** [comment]
Actual error while enabling OAuth:

```com.google.api.client.auth.oauth2.TokenResponseException: 403 Forbidden
{
  "kind" : "Status",
  "apiVersion" : "v1",
  "metadata" : { },
  "status" : "Failure",
  "message" : "forbidden: User \"system:anonymous\" cannot post path \"/oauth/token\"",
  "reason" : "Forbidden",
  "details" : { },
  "code" : 403
}```

Looks related to the SA Jenkins Pod uses, but not validated yet

**Comment by makentenza** [comment]
@InfoSec812 I'm closing this issue as the image coming with the GA version is working ok with OAuth. I'll open a new one so we can adapt our Jenkins s2i process to run in v4.1 as now is broken
