### ISSUE TITLE
Fail but continue for post_steps for Nexus repo configuration

### ISSUE THREAD

**Issue by pcarney8** [rht-labs/labs-ci-cd#279]
If the `config-nexus` role fails due to Nexus' API changing, it holds up the entire `labs-ci-cd` deployment.

We should debug the failure out, but then continue on the `labs-ci-cd` deployment, Failing to deploy the entire stack because the Nexus API has changed and doesn't have our scripts is not a great look.

Thoughts @oybed @springdo @InfoSec812

**Comment by springdo** [comment]
Could not agree more @pcarney8! This drives me mad when Nexus does this. Also, it could help us fix issues around changing nexus default password through automation and then being able to reapply the inventory without it fail at this step

**Comment by mcanoy** [comment]
https://github.com/redhat-cop/openshift-templates/pull/48

This pr removes the need for config-nexus. Also auto-captures password for 3.17+ and can provided a password if needed

**Comment by pcarney8** [comment]
closing due to #295 will fix this and @mcanoy 's comments
