### ISSUE TITLE
Ansible 2.8 causes issues with 'delegate_to'

### ISSUE THREAD

**Issue by srahilly** [rht-labs/labs-ci-cd#281]
In 1. The Manual Menace, step 10, an Ansible Playbook is run for the first time

ansible-playbook apply.yml -i inventory/ -e target=bootstrap

With Ansible 2.8 (Latest on June 3 2019), there is an error of
'delegate_to' is not a valid attribute for a TaskInclude
https://github.com/kubernetes-sigs/kubespray/issues/3985

I was able to resolve the issue by setting a variable
export ANSIBLE_INVALID_TASK_ATTRIBUTE_FAILED=False

**Comment by jacobsee** [comment]
This should have been fixed as of the new release 11 days ago.
Can you confirm that your local copy is up-to-date?

**Comment by srahilly** [comment]
I ran git clone https://github.com/RedHatTraining/rht-labs-ci-cd enablement-ci-cd around 1700 BST (London) yesterday. 
git-pull-all.sh is dated 7 Jun 18:16
Is there a version file I can check?

**Comment by oybed** [comment]
Please open issue against  https://github.com/RedHatTraining/rht-labs-ci-cd as that's where this problem exists. I.e.: this line needs to be updated to version `2.0.10`: https://github.com/RedHatTraining/rht-labs-ci-cd/blob/master/requirements.yml#L7

**Comment by oybed** [comment]
FYI: new PRs have been opened against https://github.com/RedHatTraining/rht-labs-ci-cd/pulls
