### ISSUE TITLE
Jenkins s2i and OCP v4.1

### ISSUE THREAD

**Issue by makentenza** [rht-labs/labs-ci-cd#282]
With OCP v4.1 being GA we need to update how we build our own Jenkins using s2i as the actual code won't work anymore.

**Comment by pcarney8** [comment]
@makentenza this needs some more details on what exactly doesn't work. Also if it is related to the s2i jenkins configuration, is the issue better suited here: https://github.com/rht-labs/s2i-config-jenkins

**Comment by pcarney8** [comment]
@makentenza can we close this?
