### ISSUE TITLE
What are the node memory requirements to deploy labs-ci-cd? 

### ISSUE THREAD

**Issue by sensiblemedia** [rht-labs/labs-ci-cd#39]
Hi,

What are the node memory requirements to deploy labs-ci-cd? 
Asking as attempting to deploy on a single node standalone (oc cluster up) cluster?

Thanks
SRG

**Comment by sherl0cks** [comment]
@sensiblemedia our target environments are always multi clusters deployed via https://github.com/redhat-cop/casl-ansible. I don't think we've ever done any testing in a low memory environment, that's not really the use case for this tooling.
