### ISSUE TITLE
Determine a Versioning Scheme

### ISSUE THREAD

**Issue by sherl0cks** [rht-labs/labs-ci-cd#47]
Once #44, https://github.com/rht-labs/openshift-jenkins-s2i-config/issues/52 and https://github.com/rht-labs/openshift-sonarqube/issues/16 are merged, we need to cut a release of this repo.

Before doing that, we should decided on a versioning schem.

**Comment by oybed** [comment]
A pre-release was cut to have a "fall-back" strategy before merging the big clean-up PRs. This pre-release is using `vX.Y.Z` versioning scheme, but this can always be revamped before cutting the "v1" release.

https://github.com/rht-labs/labs-ci-cd/releases/tag/v0.1.0

**Comment by sherl0cks** [comment]
Good call. Thank you. 

@oybed is there a versioning scheme in casl we can follow?

**Comment by oybed** [comment]
@sherl0cks CASL is following **major.minor** OpenShift releases and uses the `vX.Y.Z` approach:
https://github.com/redhat-cop/casl-ansible/releases

**Comment by sherl0cks** [comment]
we've started this with https://github.com/rht-labs/labs-ci-cd/releases/tag/v3.6.0
