### ISSUE TITLE
clean up sonar docker build

### ISSUE THREAD

**Issue by sherl0cks** [rht-labs/labs-ci-cd#56]
These are carry over issues from after the merge: https://github.com/rht-labs/openshift-sonarqube/issues/18

**Comment by InfoSec812** [comment]
SONAR_WEB_JVM_OPTS is still in use [HERE](https://github.com/rht-labs/openshift-sonarqube/blob/master/run.sh#L25)

SONAR_PLUGINS_LIST is still used [HERE](https://github.com/rht-labs/openshift-sonarqube/blob/master/plugins.sh#L12)

**Comment by sherl0cks** [comment]
@InfoSec812 

- for `SONAR_WEB_JVM_OPTS`, ah ok, missed that.
- for `SONAR_PLUGINS_LIST`, my reading of https://github.com/rht-labs/labs-ci-cd/blob/master/docker/sonarqube/Dockerfile#L10 is such that the values used in https://github.com/rht-labs/labs-ci-cd/blob/master/docker/sonarqube/plugins.sh#L12 are hard coded.

**Comment by InfoSec812** [comment]
Yep, you're right... The list IS hard coded.

**Comment by sherl0cks** [comment]
Ok - should we remove `SONAR_PLUGINS_LIST` or just set those values to the default on the template?

**Comment by InfoSec812** [comment]
We can remove it I believe.

**Comment by InfoSec812** [comment]
Fixed
