### ISSUE TITLE
sonar bash scripts should be improved

### ISSUE THREAD

**Issue by oybed** [rht-labs/labs-ci-cd#59]
The sonar bash scripts should be improved - i.e.:
- random sleeps (i.e.: `sleep 20) - these should be either removed or changed to be better logic
- a not unnecessary negative logic - i.e.: `! -z` that can be written as `-n` 
- should be enhanced to be part of s2i assemble process rather than Dockerfile

https://github.com/rht-labs/labs-ci-cd/blob/master/docker/sonarqube/run.sh
https://github.com/rht-labs/labs-ci-cd/blob/master/docker/sonarqube/plugins.sh

**Comment by sherl0cks** [comment]
no longer lives here and appears to be resolved in https://github.com/redhat-cop/containers-quickstarts/tree/master/sonarqube
