### ISSUE TITLE
Jenkins Slave Image Needs to Be Pinned to OpenShift Versions

### ISSUE THREAD

**Issue by sherl0cks** [rht-labs/labs-ci-cd#65]
https://github.com/openshift/origin/issues/17019 is being caused by mismatch of OC client in the slave to the OCP server.

https://access.redhat.com/containers/#/registry.access.redhat.com/openshift3/jenkins-slave-base-rhel7/images/v3.6.173.0.49-5 works with OCP v3.6.173.0.21

**Comment by springdo** [comment]
We're moving slaves out of this repo; so this issue should go too.
