### ISSUE TITLE
Complete Slack Integration or Remove Slack and Support Hubot

### ISSUE THREAD

**Issue by sherl0cks** [rht-labs/labs-ci-cd#73]
[our current slack integration with Jenkins](https://github.com/rht-labs/labs-ci-cd/tree/master/s2i-config/jenkins-master#slack-integration) requires a deployment config that supports the custom env variables for slack integration. the current inventory uses the [out of the box ephemeral template](https://github.com/rht-labs/labs-ci-cd/blob/master/inventory/group_vars/all.yml#L49) which does not support these env vars, and [we also don't have post roles in the openshift applier](https://github.com/redhat-cop/casl-ansible/issues/133) yet which would allow us to add such vars. so one of a few things needs to happen (in order of my preference):

- drop the existing jenkins integration with slack in favor of a hubot deployment (@mcanoy has prototype work here)
- add a post role (once available) to add the env vars needed to make the existing integration work
- provide a custom jenkins deployment config to support the existing slack integration

**Comment by springdo** [comment]
Or if people want to use Mattermost; I've already gone ahead with some prototyping on it....
https://github.com/springdo/mattermost-ocp

**Comment by sherl0cks** [comment]
Closed for https://github.com/rht-labs/s2i-config-jenkins/issues/5
