### ISSUE TITLE
move *-build-pod to jenkins-slave-*

### ISSUE THREAD

**Issue by sherl0cks** [rht-labs/labs-ci-cd#75]
the term build pod is confusing. replace with jenkins slave a la https://github.com/rht-labs/labs-ci-cd/tree/master/docker/jenkins-slave-ansible

**Comment by pcarney8** [comment]
@sherl0cks do you want it `ansible-jenkins-slave` or `jenkins-slave-ansible`? i noticed `mvn-jenkins-slave` and `npm-jenkins-slave` in there currently. I'm going to go through make all the naming conventions the same, just let me know which way you prefer.

**Comment by sherl0cks** [comment]
I have waffled back and forth. which do you think reads better? i'm open on this

**Comment by pcarney8** [comment]
well, after i just refactored to `*-jenkins-slave` I realized it jumbles everything up, aka they're not all right next to each other in the file system. I think having `jenkins-slave-*` at least groups them together when they are in alphabetical order, so it makes them easier to find

**Comment by sherl0cks** [comment]
sounds good to me.

**Comment by springdo** [comment]
Im in favour of the @pcarney8 suggestion -  `jenkins-slave-${BUILDER_NAME}` tbh. I like how it reads with similar items grouped together and as this repo grows, plus the types of these we may encounter in the future; it could be useful having them grouped.

**Comment by sherl0cks** [comment]
agreed and I do believe this is the approach taken in #76

**Comment by sherl0cks** [comment]
resolved by 76
