### ISSUE TITLE
ZAP Jenkins Slave Build Fails Irreguarly

### ISSUE THREAD

**Issue by sherl0cks** [rht-labs/labs-ci-cd#80]
See attached build log. This is on OCP 3.7. I'm just running the inventory, nothing special.

[zap-build-pod-1-build.log](https://github.com/rht-labs/labs-ci-cd/files/1623458/zap-build-pod-1-build.log)

**Comment by InfoSec812** [comment]
The logs indicate this is a problem accessing the EPEL repositories... We could potentially resolve this by using RHEL7 base images, but that may require SCL to function properly. I will look into it as time permits.

**Comment by springdo** [comment]
There were problems a while ago with repos not avail in rhel land but they're fixed now; perhaps this was linked to that? 
Having used the ZAP image loads over past few months on residency, we did not see these errors happen. 
There is now a PR to move ZAP to container-quickstarts so let's capture any new issues we see with this over there.
