### ISSUE TITLE
Add Automation To Configure Nexus with the Proper Repos

### ISSUE THREAD

**Issue by sherl0cks** [rht-labs/labs-ci-cd#91]
https://github.com/rht-labs/ansible-stacks/tree/master/roles/configure-nexus

**Comment by springdo** [comment]
Link above is dead but most of this work is already done if im not mistaken. I've added some more in my PR #166

**Comment by pcarney8** [comment]
yeah this is done: https://github.com/rht-labs/labs-ci-cd/blob/v3.10.0/roles/configure-nexus/tasks/configure-repos.yml#L23
