### ISSUE TITLE
provide git webhook trigger support in pipeline s2i-app-build templates

### ISSUE THREAD

**Issue by mcanoy** [rht-labs/labs-ci-cd#94]
When create a build config it would be nice to support gitlab / github triggers in the [s2i-app-build templates](https://github.com/rht-labs/labs-ci-cd/tree/master/openshift-templates/s2i-app-build)

Should work if you need it or not.

**Comment by sherl0cks** [comment]
resolved by #94

@JoshuaTPritchett make sure to put `resolved` in front of the issue number in your PR to automatically close the relevant issue
